version: '3.1'

services:

  # app:
  #   build:
  #     dockerfile: docker/Dockerfile
  #     context: .
  #   depends_on:
  #     - mongo
  #   environment:
  #     DB_HOST: db
  #   volumes:
  #     - ./src:/app/src
  #     - ./migrations:/app/migrations
  #     - ./alembic.ini:/app/alembic.ini
  #   ports:
  #     - 8000:8000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: lappis
      ME_CONFIG_MONGODB_ADMINPASSWORD: lappis
      ME_CONFIG_MONGODB_URL: mongodb://lappis:lappis@mongo:27017/